version: "3.9"
   
services:
  db:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - ./data/db:/var/lib/mariadb/data
    ports:
      - "3302:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MARIADB_ROOT_PASSWORD=passs
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8085
    volumes:
      - .:/code
    ports:
      - "8085:8085"
    environment:
      - MARIADB_ROOT_PASSWORD=passs
    depends_on:
      - db