# Generated by Django 4.0.4 on 2022-07-03 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_user', '0002_membre_photo_alter_membre_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membre', to=settings.AUTH_USER_MODEL),
        ),
    ]
