# Generated by Django 4.0.4 on 2022-07-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_user', '0003_alter_membre_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='profil',
            new_name='fonction',
        ),
    ]
