# Generated by Django 4.0.4 on 2022-07-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_user', '0004_rename_profil_membre_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('membre', 'membre')], default='membre', max_length=100),
        ),
    ]
