# Generated by Django 4.0.4 on 2022-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_user', '0005_membre_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='description',
            field=models.TextField(blank=True, default='description', max_length=500),
        ),
        migrations.AlterField(
            model_name='membre',
            name='fonction',
            field=models.CharField(blank=True, default='fonction', max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='quartier',
            field=models.CharField(blank=True, default='quartier', max_length=100),
        ),
        migrations.AlterField(
            model_name='membre',
            name='ville',
            field=models.CharField(blank=True, default='ville', max_length=100),
        ),
    ]
