# Generated by Django 4.0.4 on 2022-07-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_user', '0008_membre_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('etat 1', 'etat1'), ('etat 2', 'etat2'), ('etat 3', 'etat3')], max_length=20)),
                ('intitule', models.CharField(max_length=100)),
                ('progression', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('membres', models.ManyToManyField(to='gestion_user.membre')),
            ],
        ),
    ]
