# Generated by Django 4.0.4 on 2022-07-11 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_user', '0008_membre_date_created'),
        ('projets', '0002_alter_tache_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='progression',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='Brève description du projet', max_length=500)),
                ('progression', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('membres', models.ManyToManyField(to='gestion_user.membre')),
                ('taches', models.ManyToManyField(to='projets.tache')),
            ],
        ),
    ]
