# Generated by Django 4.0.4 on 2022-07-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_projet_visibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
